### ISSUE TITLE
Ability to consume GitDepend.json

### ISSUE THREAD

**Issue by kjjuno** [kjjuno/GitDepend#1]
This is a critical feature. Almost everything else in the product will need to use the information from GitDepend.yml. There needs to be a way to read in GitDepend.yml and represent the data as an in memory object.

The format of the file is as follows

```
build:
  script: make.bat
packages:
  dir: artifacts/NuGet/Debug
dependencies:
  LibA:
    url: ssh://git@github.com:kjjuno/liba.git
    dir: ../LibA
    branch: develop
  LibB:
    url: ssh://git@github.com:kjjuno/liba.git
    dir: ../LibB
    branch: develop
```
